[package]
name = "lab05"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.13", features = ["derive"] }
sha2 = "0.10.6"
rsa = "0.7.0"
rand = "0.8.5"
signature = "1.6.4"
